M48
; DRILL file {KiCad 8.0.5-8.0.5-0~ubuntu22.04.1} date 2024-10-15T18:41:08+0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-10-15T18:41:08+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.5-8.0.5-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.900
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.200
%
G90
G05
T1
X159.0Y-80.125
X159.0Y-85.125
T2
X118.0Y-74.5
X118.0Y-77.5
T3
X120.0Y-67.0
X120.0Y-100.5
X159.0Y-100.0
X159.5Y-67.0
M30
